### ISSUE TITLE
NPM error trying to install expo version

### ISSUE THREAD

**Issue by Toweoner** [WrathChaos/react-native-dynamic-search-bar#30]
When I try to install the "Expo version" with command: `npm i Wrath Chaos/react-native-dynamic-search-bar#expo` I receive the following error:

```
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > @expo/vector-icons@10.0.6 prepare C:\Users\user\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-eb8ba27f
npm ERR! prepareGitDep > expo-module prepare && npm run generate-lazy && npm run copy-vendor
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep C:\Users\user\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-eb8ba27f\node_modules\expo-module-scripts\bin\expo-module-prepare:3
npm ERR! prepareGitDep set -eo pipefail
npm ERR! prepareGitDep         ^^^^^^^^
npm ERR! prepareGitDep
npm ERR! prepareGitDep SyntaxError: Unexpected identifier
npm ERR! prepareGitDep     at wrapSafe (internal/modules/cjs/loader.js:1070:16)
npm ERR! prepareGitDep     at Module._compile (internal/modules/cjs/loader.js:1120:27)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:1000:32)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
npm ERR! prepareGitDep     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
npm ERR! prepareGitDep     at internal/main/run_main_module.js:18:47
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! @expo/vector-icons@10.0.6 prepare: `expo-module prepare && npm run generate-lazy && npm run copy-vendor`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the @expo/vector-icons@10.0.6 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-04-30T12_01_05_745Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-04-30T12_01_05_909Z-debug.log
```

Any idea?

**Comment by Tecnochii** [comment]
How did you fix it?

**Comment by WrathChaos** [comment]
@Tecnochii Do you still get this error?

**Comment by Tecnochii** [comment]
> @Tecnochii I have the same problem, but in another project, here is the only place where I saw the same problem. I would like to know if you would be so kind to tell me how you solved it.

**Comment by bombillazo** [comment]
Any update on the root cause of this error?
